KNOWLEDGE_BASE = [
    {
        "id": "faq_hours",
        "content": "Our sales gallery call center operates 24/7, including weekends and public holidays. You can reach us at 019-4362940. For direct sales gallery visits, our physical location is open from 10 AM to 6 PM daily. Appointments are highly recommended.",
        "keywords": [
            "hours",
            "contact",
            "support",
            "call center",
            "operating hours",
            "gallery hours",
        ],
    },
    {
        "id": "faq_password_reset",
        "content": "This AI assistant does not handle password resets for external accounts. For any login or account issues related to our website, please visit our account recovery page at example.com/reset-password. You will need your registered email address or phone number.",
        "keywords": ["password", "reset", "account", "email", "phone", "login"],
    },
    {
        "id": "prod_features_gamuda_gardens",
        "content": "Gamuda Gardens, located in Rawang, Selangor, offers a holistic living experience with 50-acre parks, five cascading lakes, and a Waterfront Village. It features diverse home types including link homes, garden villas, and semi-detached houses, ranging from 1,800 sqft to 3,000 sqft. Prices start from RM 850,000. It emphasizes nature-inspired living with excellent connectivity to major highways.",
        "keywords": [
            "gamuda gardens",
            "rawang",
            "selangor",
            "township",
            "park",
            "lake",
            "link homes",
            "villas",
            "semi-detached",
            "sqft",
            "price",
            "nature",
            "connectivity",
        ],
    },
    {
        "id": "prod_features_quayside",  #
        "content": "The Quayside at Gamuda Cove, located in Southern Klang Valley near Kuala Langat, is a vibrant residential precinct. It offers serviced apartments and commercial lots with direct access to the 23-acre central park, a 50-acre pet-friendly park, and a water theme park. Units are compact and modern, starting from 600 sqft. Prices begin at RM 450,000, ideal for young professionals and families.",
        "keywords": [
            "quayside",
            "gamuda cove",
            "klang valley",
            "serviced apartments",
            "commercial lots",
            "central park",
            "water theme park",
            "pet-friendly",
            "sqft",
            "price",
            "klia",
            "elite highway",
        ],
    },
    {
        "id": "prod_features_highpark_suites",  # Specific to Gamuda - HighPark Suites
        "content": "HighPark Suites in Kelana Jaya, Petaling Jaya, is an eco-friendly high-rise development focused on sustainable urban living. It offers studio and 2-bedroom units from 450 sqft to 850 sqft. Features include rainwater harvesting, energy-efficient fittings, a dedicated fitness park, and a sky court. It's strategically located with easy access to LRT stations and major commercial hubs. Prices start from RM 580,000.",
        "keywords": [
            "highpark suites",
            "kelana jaya",
            "petaling jaya",
            "eco-friendly",
            "high-rise",
            "studio",
            "2-bedroom",
            "sqft",
            "price",
            "lrt",
            "sustainable",
        ],
    },
    {
        "id": "gamuda_overview",
        "content": "Gamuda Land is a leading property developer in Malaysia known for creating sustainable townships and communities with unique placemaking. Their developments often feature extensive green spaces, comprehensive amenities, and focus on livability and community building.",
        "keywords": [
            "gamuda land",
            "developer",
            "townships",
            "community",
            "placemaking",
            "green spaces",
            "malaysia",
        ],
    },
    {
        "id": "appointment_info",
        "content": "To schedule a gallery visit, we need to understand your preferences first, such as your budget, family size, and what features are most important to you (your 'non-negotiables'). This helps us tailor the visit to your needs. Appointments are subject to sales personnel availability.",
        "keywords": [
            "appointment",
            "schedule",
            "visit",
            "gallery",
            "booking",
            "availability",
        ],
    },
    {
        "id": "agent_role",
        "content": "I am an AI assistant designed to help you with property sales gallery inquiries, provide product information, and assist in scheduling appointments with our sales personnel. I do not provide legal, financial, or investment advice.",
        "keywords": ["AI assistant", "role", "help", "information", "appointment"],
    },
    {
        "id": "customer_details_prompt",
        "content": "To help me understand your needs better, could you please tell me your name, your approximate budget for a property, what are your must-have features or 'non-negotiables' for a property, your intention to buy (e.g., immediate, within 6 months, just Browse), your marital status, family size, and your current location?",
        "keywords": [
            "customer details",
            "name",
            "budget",
            "non-negotiables",
            "intention to buy",
            "marital status",
            "family size",
            "current location",
        ],
    },
    {
        "id": "off_topic_response",
        "content": "My purpose is to assist with property sales gallery inquiries. If you have other questions related to properties, I'd be happy to help. Otherwise, I might need to end this call.",
        "keywords": ["off-topic", "redirect", "end call"],
    },
]
