/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/calendar/': RouteRecordInfo<'/calendar/', '/calendar', Record<never, never>, Record<never, never>>,
    '/Database': RouteRecordInfo<'/Database', '/Database', Record<never, never>, Record<never, never>>,
    '/oncall-page': RouteRecordInfo<'/oncall-page', '/oncall-page', Record<never, never>, Record<never, never>>,
    '/anything': RouteRecordInfo<'/anything', '/anything', Record<never, never>, Record<never, never>>,
    '/CustomerCallSummary': RouteRecordInfo<'/CustomerCallSummary', '/CustomerCallSummary', Record<never, never>, Record<never, never>>,
  }
}
