/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/faq-database/': RouteRecordInfo<'/admin/faq-database/', '/admin/faq-database', Record<never, never>, Record<never, never>>,
    '/call-summary/': RouteRecordInfo<'/call-summary/', '/call-summary', Record<never, never>, Record<never, never>>,
    '/on-call/': RouteRecordInfo<'/on-call/', '/on-call', Record<never, never>, Record<never, never>>,
    '/stream-tts': RouteRecordInfo<'/stream-tts', '/stream-tts', Record<never, never>, Record<never, never>>,
    '/stt': RouteRecordInfo<'/stt', '/stt', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
  }
}
